### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by conspacer** [franciskim/slackslime#6]
Is this project still being maintained? Its a very interesting idea, but since the last commit is a year ago I thought to ask before giving install fail details.

**Comment by franciskim** [comment]
Hey there @conspacer - not really maintained as such but I can try help

**Comment by conspacer** [comment]
hi @franciskim . I actually just poked around and figured out a way to start the script
Machine runs latest Debian Jessie.

First was the command `npm install slackslime` throws some errors about missing package.json (and some other files). I ignored this.
Second was running the command as instructed `nodejs [channel name] [RTM API token 1] [RTM API token 2]` returns error "no such module {the channel name I used}". I tired by running from the slackslime dir in the node_modules dir and added `nodejs slackslime.js [channel name] [RTM API token 1]...`.
It is running in verbose mode now (I have it running in a detached tmux session).

**Questions:** 
1. Is this the correct way to start the script? 
2. How about running multiple configurations?
3. Is there a way to run it in the background?

**Comment by conspacer** [comment]
I start the script now with [Forever](https://github.com/indexzero/forever). So far its working well with multiple configurations. Ill update after a few days of testing.
Note: Update to the [proper Forever](https://github.com/foreverjs/forever) repo link...)

**Comment by conspacer** [comment]
Small update: Private channels seams to not work even with the bot included in the channel members.
```
01:35:35s 701ms [Transport] [SlackAPI]      Connected as botusername[U3UU82NKW]. 
01:35:36s 117ms [Transport] [SlackAPI]      Received: {"type":"hello"} 
/home/user/node_modules/slackslime/slackslime.js:33  
        this.channelId = this.getChannel(slackslime.channelName).id; 
                                                                ^                       
TypeError: Cannot read property 'id' of null
```

**Comment by franciskim** [comment]
@conspacer I've never tested this on private channels. I prefer PM2 over Forever but if it works why not.

So I guess you got it working now? Feel free to submit a pull request if you think you can fix the issue for private channels! 

Let me know if you still have pending questions otherwise I'll close this issue soonish, thanks!

**Comment by conspacer** [comment]
@franciskim I don't think I can fix the private channel issue, it still does not work. 
Otherwise its working perfectly in regular channels. Great pc. of software. Tx.
You can close the issue.

**Comment by franciskim** [comment]
Might be a restriction with the API. Thanks for the kind words.
